// GENERATED by agents/compile.mjs from agents/profiles/*.json — DO NOT EDIT.
// Run `node scripts/compile-registries.mjs` (wired into the CLI build/test) to regenerate.

export type WireProtocol = "anthropic-messages" | "openai-chat" | "openai-responses" | "gemini-generatecontent";

export type Injection =
  | { method: "env"; env: Record<string, string> }
  | { method: "config-env-content"; env_var: string; config_content: { local: unknown; managed?: unknown } }
  | { method: "config-file"; env_var: string; base_config?: { path: string; env_var?: string; state_dir?: { env_var: string; filename: string }; platform_default?: "qwen-system-settings" }; config_overlay: { local: unknown; managed?: unknown } }
  | { method: "native-extension"; host: string; asset: string; loader_flag: string };

export type CommandHook =
  | { method: "claude-pretooluse" }
  | { method: "codex-pretooluse"; file: string }
  | { method: "gemini-beforetool" }
  | { method: "opencode-plugin" }
  | { method: "hermes-plugin" }
  | { method: "openclaw-plugin" }
  | { method: "pi-extension" }
  | { method: "instruction-note"; file: string };

export type MemoryHook =
  | { method: "claude-userpromptsubmit" };

export type SkillsSurface = { format: "skill-md"; user_dirs: string[]; project_dirs?: string[] };

export interface AgentProfile {
  schema_version: string;
  id: string;
  display_name: string;
  vendor: string;
  homepage: string;
  binary_names: string[];
  args: string[];
  install: string;
  wire_protocol: WireProtocol;
  injection: Injection;
  command_hook?: CommandHook;
  memory_hook?: MemoryHook;
  skills?: SkillsSurface;
  attribution?: { header?: string };
  tested_agent_version?: string;
  injection_completeness?: "declarative" | "builder-assisted" | "code-only";
  last_verified_at?: string;
  verified_by?: string;
  fallback?: string;
  maintainer?: string | null;
}

export const PROFILES: AgentProfile[] = [
  {
    "schema_version": "1",
    "id": "aider",
    "display_name": "Aider",
    "vendor": "OpenAI / Anthropic",
    "homepage": "https://aider.chat/docs/llms/openai-compat.html",
    "binary_names": [
      "aider"
    ],
    "args": [],
    "install": "python -m pip install aider-chat",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "env",
      "env": {
        "OPENAI_API_BASE": "{{cave_base_url}}/openai/v1"
      }
    },
    "attribution": {
      "header": "x-cave-agent"
    },
    "tested_agent_version": "0.86.2",
    "injection_completeness": "declarative",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "claude",
    "display_name": "Claude Code",
    "vendor": "Anthropic",
    "homepage": "https://code.claude.com/docs",
    "binary_names": [
      "claude"
    ],
    "args": [],
    "install": "npm i -g @anthropic-ai/claude-code",
    "wire_protocol": "anthropic-messages",
    "injection": {
      "method": "env",
      "env": {
        "ANTHROPIC_BASE_URL": "{{cave_base_url}}",
        "ANTHROPIC_AUTH_TOKEN": "{{cave_api_key}}"
      }
    },
    "skills": {
      "format": "skill-md",
      "user_dirs": [
        "~/.claude/skills"
      ],
      "project_dirs": [
        ".claude/skills"
      ]
    },
    "command_hook": {
      "method": "claude-pretooluse"
    },
    "memory_hook": {
      "method": "claude-userpromptsubmit"
    },
    "attribution": {
      "header": "x-cave-agent"
    },
    "tested_agent_version": "2.1.291",
    "injection_completeness": "builder-assisted",
    "last_verified_at": "2026-10-06",
    "verified_by": "local pinned-binary probe (claude 2.1.291 on Node 22.22.2, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "codex",
    "display_name": "OpenAI Codex CLI",
    "vendor": "OpenAI",
    "homepage": "https://developers.openai.com/codex",
    "binary_names": [
      "codex"
    ],
    "args": [],
    "install": "npm i -g @openai/codex",
    "wire_protocol": "openai-responses",
    "injection": {
      "method": "env",
      "env": {}
    },
    "skills": {
      "format": "skill-md",
      "user_dirs": [
        "~/.codex/skills"
      ],
      "project_dirs": []
    },
    "command_hook": {
      "method": "codex-pretooluse",
      "file": "~/.codex/AGENTS.md"
    },
    "attribution": {
      "header": "x-cave-agent"
    },
    "tested_agent_version": "0.160.1",
    "injection_completeness": "code-only",
    "last_verified_at": "2026-10-06",
    "verified_by": "local pinned-binary probe (codex 0.160.1 on Node 24.16.0, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "gemini",
    "display_name": "Gemini CLI",
    "vendor": "Google",
    "homepage": "https://github.com/google-gemini/gemini-cli",
    "binary_names": [
      "gemini"
    ],
    "args": [],
    "install": "npm i -g @google/gemini-cli",
    "wire_protocol": "gemini-generatecontent",
    "injection": {
      "method": "env",
      "env": {
        "GOOGLE_GEMINI_BASE_URL": "{{cave_base_url}}",
        "GOOGLE_VERTEX_BASE_URL": "{{cave_base_url}}/vertex"
      }
    },
    "command_hook": {
      "method": "gemini-beforetool"
    },
    "attribution": {
      "header": "x-cave-agent"
    },
    "tested_agent_version": "0.62.0",
    "injection_completeness": "declarative",
    "last_verified_at": "2026-10-03",
    "verified_by": "local pinned-binary probe (gemini 0.62.0 on Node 24.16.0, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "hermes",
    "display_name": "Hermes Agent",
    "vendor": "Nous Research",
    "homepage": "https://hermes-agent.nousresearch.com/docs/",
    "binary_names": [
      "hermes"
    ],
    "args": [
      "--provider",
      "custom"
    ],
    "install": "curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "env",
      "env": {
        "CUSTOM_BASE_URL": "{{cave_base_url}}/v1",
        "CUSTOM_API_KEY": "{{cave_api_key}}"
      }
    },
    "command_hook": {
      "method": "hermes-plugin"
    },
    "attribution": {
      "header": "x-cave-agent"
    },
    "tested_agent_version": "0.21.5",
    "injection_completeness": "builder-assisted",
    "last_verified_at": "2026-10-06",
    "verified_by": "local pinned-binary probe (hermes 0.21.5 = release v2026.9.24 at f97608f1, editable install on Python 3.12, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "kilo",
    "display_name": "Kilo Code",
    "vendor": "Kilo Code",
    "homepage": "https://kilo.ai/docs/code-with-ai/platforms/cli",
    "binary_names": [
      "kilo",
      "kilocode"
    ],
    "args": [],
    "install": "npm install -g @kilocode/cli@7.8.3",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "config-env-content",
      "env_var": "KILO_CONFIG_CONTENT",
      "config_content": {
        "local": {
          "provider": {
            "caveman": {
              "npm": "@ai-sdk/openai-compatible",
              "name": "Caveman Local Proxy",
              "options": {
                "baseURL": "{{cave_base_url}}/v1",
                "apiKey": "{env:OPENAI_API_KEY}",
                "headers": {
                  "X-Cave-Agent": "kilo"
                }
              },
              "models": {
                "gpt-5.5": {
                  "name": "GPT-5.5 (via Caveman)",
                  "tool_call": true,
                  "limit": {
                    "context": 1050000,
                    "output": 32768
                  }
                },
                "gpt-5.4-mini": {
                  "name": "GPT-5.4 mini (via Caveman)",
                  "tool_call": true,
                  "limit": {
                    "context": 400000,
                    "output": 16384
                  }
                }
              }
            }
          },
          "model": "caveman/gpt-5.5",
          "enabled_providers": [
            "caveman"
          ]
        },
        "managed": {
          "provider": {
            "caveman": {
              "npm": "@ai-sdk/openai-compatible",
              "name": "Caveman Gateway",
              "options": {
                "baseURL": "{{cave_base_url}}/v1",
                "apiKey": "{env:CAVE_API_KEY}",
                "headers": {
                  "x-cave-upstream-key": "{{cave_optional_openai_key_env}}",
                  "X-Cave-Agent": "kilo"
                }
              },
              "models": {
                "gpt-5.5": {
                  "name": "GPT-5.5 (via Caveman)",
                  "tool_call": true,
                  "limit": {
                    "context": 1050000,
                    "output": 32768
                  }
                },
                "gpt-5.4-mini": {
                  "name": "GPT-5.4 mini (via Caveman)",
                  "tool_call": true,
                  "limit": {
                    "context": 400000,
                    "output": 16384
                  }
                }
              }
            }
          },
          "model": "caveman/gpt-5.5",
          "enabled_providers": [
            "caveman"
          ]
        }
      }
    },
    "attribution": {
      "header": "X-Cave-Agent"
    },
    "tested_agent_version": "7.8.3",
    "injection_completeness": "declarative",
    "last_verified_at": "2026-10-03",
    "verified_by": "local pinned-binary probe (kilo 7.8.3 on Node 24.16.0, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "openclaw",
    "display_name": "OpenClaw",
    "vendor": "OpenClaw",
    "homepage": "https://github.com/openclaw/openclaw#readme",
    "binary_names": [
      "openclaw"
    ],
    "args": [
      "chat"
    ],
    "install": "npm i -g openclaw",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "config-file",
      "env_var": "OPENCLAW_CONFIG_PATH",
      "base_config": {
        "path": "~/.openclaw/openclaw.json",
        "env_var": "OPENCLAW_CONFIG_PATH",
        "state_dir": {
          "env_var": "OPENCLAW_STATE_DIR",
          "filename": "openclaw.json"
        }
      },
      "config_overlay": {
        "local": {
          "mcp": {
            "servers": {
              "caveman": {
                "command": "caveman-mcp",
                "args": []
              }
            }
          }
        },
        "managed": {
          "mcp": {
            "servers": {
              "caveman": {
                "command": "caveman-mcp",
                "args": []
              }
            }
          }
        }
      }
    },
    "command_hook": {
      "method": "openclaw-plugin"
    },
    "attribution": {
      "header": "x-cave-agent"
    },
    "tested_agent_version": "2026.9.8",
    "injection_completeness": "builder-assisted",
    "last_verified_at": "2026-10-03",
    "verified_by": "local pinned-binary probe (openclaw 2026.9.8 on Node 24.16.0, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "opencode",
    "display_name": "opencode",
    "vendor": "sst",
    "homepage": "https://opencode.ai/docs/config",
    "binary_names": [
      "opencode"
    ],
    "args": [],
    "install": "npm i -g opencode-ai",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "config-env-content",
      "env_var": "OPENCODE_CONFIG_CONTENT",
      "config_content": {
        "local": {
          "$schema": "https://opencode.ai/config.json",
          "provider": {
            "openai": {
              "options": {
                "baseURL": "{{cave_base_url}}/v1",
                "headers": {
                  "X-Cave-Agent": "opencode"
                }
              }
            },
            "anthropic": {
              "options": {
                "baseURL": "{{cave_base_url}}/v1",
                "headers": {
                  "X-Cave-Agent": "opencode"
                }
              }
            },
            "opencode-go": {
              "options": {
                "baseURL": "{{cave_base_url}}/compat/opencode-go/v1",
                "headers": {
                  "X-Cave-Agent": "opencode"
                }
              }
            }
          }
        },
        "managed": {
          "$schema": "https://opencode.ai/config.json",
          "provider": {
            "caveman": {
              "npm": "@ai-sdk/openai-compatible",
              "name": "Caveman Gateway",
              "options": {
                "baseURL": "{{cave_base_url}}/v1",
                "apiKey": "{env:CAVE_API_KEY}",
                "headers": {
                  "x-cave-upstream-key": "{env:OPENAI_API_KEY}",
                  "X-Cave-Agent": "opencode"
                }
              },
              "models": {
                "gpt-5.5": {
                  "name": "GPT-5.5 (via Caveman)",
                  "limit": {
                    "context": 1050000,
                    "output": 32768
                  }
                },
                "gpt-5.4-mini": {
                  "name": "GPT-5.4 mini (via Caveman)",
                  "limit": {
                    "context": 400000,
                    "output": 16384
                  }
                }
              }
            }
          },
          "model": "caveman/gpt-5.5"
        }
      }
    },
    "command_hook": {
      "method": "opencode-plugin"
    },
    "attribution": {
      "header": "X-Cave-Agent"
    },
    "tested_agent_version": "1.18.34",
    "injection_completeness": "declarative",
    "last_verified_at": "2026-10-03",
    "verified_by": "local pinned-binary probe (opencode 1.18.34 on Node 24.16.0, agents/probe-installed.mjs)",
    "fallback": "generic-env",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "pi",
    "display_name": "Pi",
    "vendor": "pi.dev",
    "homepage": "https://pi.dev/",
    "binary_names": [
      "pi"
    ],
    "args": [],
    "install": "npm install -g --ignore-scripts @earendil-works/pi-coding-agent",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "native-extension",
      "host": "pi",
      "asset": "caveman-pi-extension",
      "loader_flag": "--extension"
    },
    "command_hook": {
      "method": "pi-extension"
    },
    "tested_agent_version": "1.0.4",
    "injection_completeness": "builder-assisted",
    "last_verified_at": "2026-10-06",
    "verified_by": "local pinned-binary probe (pi 1.0.4, agents/probe-installed.mjs); packages/pi-extension suite against pi-coding-agent 1.0.4",
    "fallback": "none",
    "maintainer": null
  },
  {
    "schema_version": "1",
    "id": "qwen",
    "display_name": "Qwen Code",
    "vendor": "QwenLM",
    "homepage": "https://github.com/QwenLM/qwen-code",
    "binary_names": [
      "qwen"
    ],
    "args": [
      "--extensions=none"
    ],
    "install": "npm i -g @qwen-code/qwen-code@0.25.0",
    "wire_protocol": "openai-chat",
    "injection": {
      "method": "config-file",
      "env_var": "QWEN_CODE_SYSTEM_SETTINGS_PATH",
      "base_config": {
        "path": "~/.qwen/system-settings.json",
        "env_var": "QWEN_CODE_SYSTEM_SETTINGS_PATH",
        "platform_default": "qwen-system-settings"
      },
      "config_overlay": {
        "local": {
          "providerProtocol": {},
          "modelProviders": {
            "openai": [
              {
                "id": "gpt-5.5",
                "name": "GPT-5.5 (via Caveman)",
                "envKey": "OPENAI_API_KEY",
                "baseUrl": "{{cave_base_url}}/v1",
                "generationConfig": {
                  "customHeaders": {
                    "X-Cave-Agent": "qwen"
                  }
                }
              },
              {
                "id": "gpt-5.4-mini",
                "name": "GPT-5.4 mini (via Caveman)",
                "envKey": "OPENAI_API_KEY",
                "baseUrl": "{{cave_base_url}}/v1",
                "generationConfig": {
                  "customHeaders": {
                    "X-Cave-Agent": "qwen"
                  }
                }
              }
            ]
          },
          "security": {
            "auth": {
              "selectedType": "openai",
              "enforcedType": "openai"
            }
          },
          "model": {
            "name": "gpt-5.5",
            "baseUrl": "{{cave_base_url}}/v1"
          },
          "modelFallbacks": "",
          "fastModel": "",
          "advisorModel": "",
          "visionModel": "",
          "compactionModel": "",
          "imageModel": "",
          "voiceModel": "",
          "disableAllHooks": true,
          "tools": {
            "webSearch": {
              "enabled": false,
              "model": ""
            },
            "workflowsEnabled": false,
            "disabled": [
              "agent",
              "skill",
              "web_search",
              "create_sub_session",
              "workflow"
            ]
          },
          "agents": {
            "builtin": {
              "exploreModel": "inherit"
            },
            "allowedGrades": []
          },
          "permissions": {
            "deny": [
              "Agent",
              "Skill",
              "WebSearch",
              "CreateSubSession",
              "Workflow"
            ]
          },
          "skills": {
            "disabledLevels": [
              "project",
              "user",
              "extension",
              "bundled"
            ]
          },
          "experimental": {
            "liveVoice": {
              "enabled": false,
              "apiKey": "",
              "model": ""
            }
          },
          "slashCommands": {
            "disabled": [
              "auth",
              "connect",
              "login",
              "model",
              "arena",
              "agents",
              "workflows",
              "settings",
              "config",
              "permissions",
              "skills",
              "voice",
              "extensions",
              "reload-plugins",
              "hooks",
              "mcp",
              "resume",
              "continue",
              "import-config"
            ]
          }
        },
        "managed": {
          "providerProtocol": {},
          "modelProviders": {
            "openai": [
              {
                "id": "gpt-5.5",
                "name": "GPT-5.5 (via Caveman)",
                "envKey": "CAVE_API_KEY",
                "baseUrl": "{{cave_base_url}}/v1",
                "generationConfig": {
                  "customHeaders": {
                    "x-cave-upstream-key": "{{cave_optional_openai_key_env}}",
                    "X-Cave-Agent": "qwen"
                  }
                }
              },
              {
                "id": "gpt-5.4-mini",
                "name": "GPT-5.4 mini (via Caveman)",
                "envKey": "CAVE_API_KEY",
                "baseUrl": "{{cave_base_url}}/v1",
                "generationConfig": {
                  "customHeaders": {
                    "x-cave-upstream-key": "{{cave_optional_openai_key_env}}",
                    "X-Cave-Agent": "qwen"
                  }
                }
              }
            ]
          },
          "security": {
            "auth": {
              "selectedType": "openai",
              "enforcedType": "openai"
            }
          },
          "model": {
            "name": "gpt-5.5",
            "baseUrl": "{{cave_base_url}}/v1"
          },
          "modelFallbacks": "",
          "fastModel": "",
          "advisorModel": "",
          "visionModel": "",
          "compactionModel": "",
          "imageModel": "",
          "voiceModel": "",
          "disableAllHooks": true,
          "tools": {
            "webSearch": {
              "enabled": false,
              "model": ""
            },
            "workflowsEnabled": false,
            "disabled": [
              "agent",
              "skill",
              "web_search",
              "create_sub_session",
              "workflow"
            ]
          },
          "agents": {
            "builtin": {
              "exploreModel": "inherit"
            },
            "allowedGrades": []
          },
          "permissions": {
            "deny": [
              "Agent",
              "Skill",
              "WebSearch",
              "CreateSubSession",
              "Workflow"
            ]
          },
          "skills": {
            "disabledLevels": [
              "project",
              "user",
              "extension",
              "bundled"
            ]
          },
          "experimental": {
            "liveVoice": {
              "enabled": false,
              "apiKey": "",
              "model": ""
            }
          },
          "slashCommands": {
            "disabled": [
              "auth",
              "connect",
              "login",
              "model",
              "arena",
              "agents",
              "workflows",
              "settings",
              "config",
              "permissions",
              "skills",
              "voice",
              "extensions",
              "reload-plugins",
              "hooks",
              "mcp",
              "resume",
              "continue",
              "import-config"
            ]
          }
        }
      }
    },
    "attribution": {
      "header": "X-Cave-Agent"
    },
    "tested_agent_version": "0.25.0",
    "injection_completeness": "declarative",
    "last_verified_at": "2026-10-06",
    "verified_by": "local pinned-binary probe (@qwen-code/qwen-code 0.25.0 on Node 24.16.0, agents/probe-installed.mjs) plus route check: the real binary, launched with the CLI buildWrapEnv overlay, sent POST /w/qwen/v1/chat/completions (X-Cave-Agent: qwen, model gpt-5.5) to a loopback recorder",
    "fallback": "generic-env",
    "maintainer": null
  }
];
